### ISSUE TITLE
Call to undefined function ImageCreate()

### ISSUE THREAD

**Issue by 501st-alpha1** [GMJH/SQRL-PHP-Library#5]
I am trying to get a server set up for testing the client I am developing, but am running into some problems.

I have Apache's `DocumentRoot` set to point to the `sample` folder in this repo. When I visit the index page, no QR code is displayed, and I see this in the logs every few seconds:

```
[Mon Jan 19 06:04:38 2015] [error] [client 192.168.200.1] PHP Fatal error:
Call to undefined function ImageCreate() in /vagrant/src/qrcode/phpqrcode.php
on line 985, referer: https://sqrl.dev/
```

Are there some dependencies I'm missing or something?

**Comment by jurgenhaas** [comment]
Sorry for that, it appears that this QR code library requires the GD extension for your PHP.  On a Debian system you could install that with `apt-get install php5-gd` and then restart Apache. I'll have a look on if and how we can make that more reliable and/or to provide alternatives.

**Comment by 501st-alpha1** [comment]
That did the trick, thanks!
